### ISSUE TITLE
Bug1 user doesn't exist

### ISSUE THREAD

**Issue by MinaYousryGhattas** [MustafaSaber/eCommerce_Application#6]
https://github.com/MustafaSaber/eCommerce_Application/blob/b97501755a150432c820332192b8d1924618be5c/src/main/java/com/ecommerce/sw2/Models/Services/UserServiceImp.java#L82
when didn't check if the user doesn't exist..  we always make foreach even Optional is empty..

**Comment by MinaYousryGhattas** [comment]
in unit testing we check only the component so we can't depend on that..

**Comment by MustafaSaber** [comment]
It's not a valid test case, In all cases a user will exsist. You doesn't need to handle a case that won't exsist.
